name: Build Server Release
on:
  push:
    branches:
      - r/**
jobs:
  build_tag:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Create new release tag
        id: build-release-tag
        uses: actions/github-script@v7
        with:
          script: |
            console.log('test');